export interface Advantage {
  id: string;
  brand: string;
  logo: string;
  discount: string;
  description: string;
  fullDescription: string;
  category: string;
  color: string;
  code?: string;
  validUntil: string;
  image: string;
}

export interface Contract {
  id: string;
  provider: string;
  type: string;
  category: 'energy' | 'insurance' | 'internet' | 'health' | 'other';
  status: 'active' | 'pending' | 'expired';
  price?: string;
  nextDate?: string;
  icon: string;
  logo: string;
}

const LOGO_TOKEN = 'pk_PVnaUxNJTB2AFk6oaM2Cug';

export const advantageCategories = [
  { id: 'all', label: 'Tout', icon: 'Grid' },
  { id: 'Maison', label: 'Maison', icon: 'Home' },
  { id: 'Mode', label: 'Mode', icon: 'Shirt' },
  { id: 'Sport', label: 'Sport', icon: 'Dumbbell' },
  { id: 'Food', label: 'Food', icon: 'UtensilsCrossed' },
  { id: 'High-Tech', label: 'High-Tech', icon: 'Smartphone' },
  { id: 'Beauté', label: 'Beauté', icon: 'Sparkles' },
  { id: 'Streaming', label: 'Streaming', icon: 'Play' },
  { id: 'Courses', label: 'Courses', icon: 'ShoppingCart' },
  { id: 'Culture', label: 'Culture', icon: 'BookOpen' },
  { id: 'Voyage', label: 'Voyage', icon: 'Plane' },
  { id: 'Services', label: 'Services', icon: 'Wrench' },
];

export const advantages: Advantage[] = [
  // Mélange varié de catégories
  {
    id: '10',
    brand: 'Netflix',
    logo: `https://img.logo.dev/netflix.com?token=${LOGO_TOKEN}`,
    discount: '2 mois',
    description: 'Offerts sur abonnement',
    fullDescription: 'Profitez de 2 mois offerts sur votre nouvel abonnement Netflix. Films, séries et documentaires en illimité.',
    category: 'Streaming',
    color: '#e50914',
    validUntil: '30 Juin 2026',
    image: 'https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?w=800&q=80',
  },
  {
    id: '2',
    brand: 'Adidas',
    logo: `https://img.logo.dev/adidas.com?token=${LOGO_TOKEN}`,
    discount: '-20%',
    description: 'Code promo exclusif',
    fullDescription: 'Bénéficiez de 20% de réduction sur toute la collection Adidas. Chaussures, vêtements et accessoires inclus. Non cumulable avec d\'autres offres.',
    category: 'Sport',
    color: '#000000',
    code: 'JADORELOC20',
    validUntil: '15 Avril 2026',
    image: 'https://images.unsplash.com/photo-1556906781-9a412961c28c?w=800&q=80',
  },
  {
    id: '1',
    brand: 'IKEA',
    logo: `https://img.logo.dev/ikea.com?token=${LOGO_TOKEN}`,
    discount: '-15%',
    description: 'Sur toute la décoration',
    fullDescription: 'Profitez de 15% de réduction sur l\'ensemble du rayon décoration IKEA. Valable en magasin et en ligne sur présentation de votre code promo exclusif.',
    category: 'Maison',
    color: '#0058a3',
    code: 'LOC15DECO',
    validUntil: '31 Mars 2026',
    image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80',
  },
  {
    id: '5',
    brand: 'Uber Eats',
    logo: `https://img.logo.dev/ubereats.com?token=${LOGO_TOKEN}`,
    discount: '-5€',
    description: 'Première commande',
    fullDescription: '5€ offerts sur votre première commande Uber Eats. Faites-vous livrer vos plats préférés directement chez vous.',
    category: 'Food',
    color: '#06c167',
    code: 'BIENVENUE5',
    validUntil: '31 Décembre 2026',
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&q=80',
  },
  {
    id: '14',
    brand: 'Zara',
    logo: `https://img.logo.dev/zara.com?token=${LOGO_TOKEN}`,
    discount: '-20%',
    description: 'Nouvelle collection',
    fullDescription: '20% de réduction sur la nouvelle collection Zara. Mode femme, homme et enfant. En magasin et en ligne.',
    category: 'Mode',
    color: '#000000',
    code: 'ZARA20NEW',
    validUntil: '15 Avril 2026',
    image: 'https://images.unsplash.com/photo-1445205170230-053b83016050?w=800&q=80',
  },
  {
    id: '4',
    brand: 'Darty',
    logo: `https://img.logo.dev/darty.com?token=${LOGO_TOKEN}`,
    discount: '-15%',
    description: 'Électroménager',
    fullDescription: 'Équipez votre logement avec 15% de réduction sur tout l\'électroménager : réfrigérateur, lave-linge, four, aspirateur et plus encore.',
    category: 'High-Tech',
    color: '#e30613',
    code: 'DARTY15NEW',
    validUntil: '28 Février 2026',
    image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80',
  },
  {
    id: '15',
    brand: 'Sephora',
    logo: `https://img.logo.dev/sephora.fr?token=${LOGO_TOKEN}`,
    discount: '-25%',
    description: 'Beauté et parfums',
    fullDescription: '25% de réduction sur une sélection de produits beauté et parfums. Maquillage, soins et coffrets inclus.',
    category: 'Beauté',
    color: '#000000',
    code: 'BEAUTY25',
    validUntil: '28 Février 2026',
    image: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=800&q=80',
  },
  {
    id: '51',
    brand: 'Booking.com',
    logo: `https://img.logo.dev/booking.com?token=${LOGO_TOKEN}`,
    discount: '-10%',
    description: 'Hébergements',
    fullDescription: '10% de réduction sur une sélection d\'hébergements Booking.com. Hôtels, appartements et maisons.',
    category: 'Voyage',
    color: '#003580',
    code: 'BOOK10LOC',
    validUntil: '31 Décembre 2026',
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
  },
  {
    id: '17',
    brand: 'Carrefour',
    logo: `https://img.logo.dev/carrefour.fr?token=${LOGO_TOKEN}`,
    discount: '-8%',
    description: 'Courses alimentaires',
    fullDescription: '8% de réduction sur vos courses en ligne Carrefour. Livraison à domicile ou retrait en drive.',
    category: 'Courses',
    color: '#004e9f',
    code: 'COURSES8',
    validUntil: '31 Décembre 2026',
    image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=800&q=80',
  },
  {
    id: '18',
    brand: 'Nike',
    logo: `https://img.logo.dev/nike.com?token=${LOGO_TOKEN}`,
    discount: '-25%',
    description: 'Membres exclusif',
    fullDescription: '25% de réduction pour les nouveaux membres Nike. Chaussures, vêtements et équipements sportifs.',
    category: 'Sport',
    color: '#000000',
    code: 'NIKE25NEW',
    validUntil: '31 Mai 2026',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80',
  },
  {
    id: '12',
    brand: 'Deliveroo',
    logo: `https://img.logo.dev/deliveroo.fr?token=${LOGO_TOKEN}`,
    discount: '-30%',
    description: '3 premières commandes',
    fullDescription: '30% de réduction sur vos 3 premières commandes Deliveroo. Découvrez les meilleurs restaurants de votre quartier.',
    category: 'Food',
    color: '#00ccbc',
    code: 'NEW30',
    validUntil: '31 Décembre 2026',
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80',
  },
  {
    id: '8',
    brand: 'Leroy Merlin',
    logo: `https://img.logo.dev/leroymerlin.fr?token=${LOGO_TOKEN}`,
    discount: '-12%',
    description: 'Aménagement intérieur',
    fullDescription: 'Profitez de 12% de réduction pour aménager et décorer votre intérieur. Peinture, revêtements, luminaires et plus.',
    category: 'Maison',
    color: '#78be20',
    code: 'LEROY12HOME',
    validUntil: '30 Juin 2026',
    image: 'https://images.unsplash.com/photo-1556909114-44e3e70034e2?w=800&q=80',
  },
  {
    id: '19',
    brand: 'H&M',
    logo: `https://img.logo.dev/hm.com?token=${LOGO_TOKEN}`,
    discount: '-15%',
    description: 'Tout le magasin',
    fullDescription: '15% de réduction sur tout le magasin H&M. Mode femme, homme, enfant et maison.',
    category: 'Mode',
    color: '#e50010',
    code: 'HM15LOC',
    validUntil: '30 Avril 2026',
    image: 'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?w=800&q=80',
  },
  {
    id: '13',
    brand: 'Spotify',
    logo: `https://img.logo.dev/spotify.com?token=${LOGO_TOKEN}`,
    discount: '3 mois',
    description: 'Premium offert',
    fullDescription: '3 mois de Spotify Premium offerts. Musique illimitée sans pub, mode hors connexion et qualité audio supérieure.',
    category: 'Streaming',
    color: '#1db954',
    validUntil: '30 Septembre 2026',
    image: 'https://images.unsplash.com/photo-1611339555312-e607c8352fd7?w=800&q=80',
  },
  {
    id: '56',
    brand: 'Wecasa',
    logo: `https://img.logo.dev/wecasa.fr?token=${LOGO_TOKEN}`,
    discount: '-15€',
    description: 'Ménage à domicile',
    fullDescription: '15€ offerts sur votre première prestation de ménage Wecasa. Professionnels certifiés.',
    category: 'Services',
    color: '#00d4aa',
    code: 'WECASA15',
    validUntil: '31 Décembre 2026',
    image: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800&q=80',
  },
  {
    id: '9',
    brand: 'Amazon',
    logo: `https://img.logo.dev/amazon.fr?token=${LOGO_TOKEN}`,
    discount: '-10€',
    description: 'Sur votre 1ère commande',
    fullDescription: '10€ de réduction sur votre première commande Amazon de 50€ minimum. Livraison gratuite incluse.',
    category: 'High-Tech',
    color: '#ff9900',
    code: 'NEWLOC10',
    validUntil: '31 Décembre 2026',
    image: 'https://images.unsplash.com/photo-1523474253046-8cd2748b5fd2?w=800&q=80',
  },
  {
    id: '7',
    brand: 'Fnac',
    logo: `https://img.logo.dev/fnac.com?token=${LOGO_TOKEN}`,
    discount: '-10%',
    description: 'Livres et multimédia',
    fullDescription: '10% de réduction sur les livres, CD, vinyles et produits multimédia. Carte Fnac non requise pour cette offre.',
    category: 'Culture',
    color: '#e1a400',
    code: 'FNAC10LOC',
    validUntil: '15 Mai 2026',
    image: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800&q=80',
  },
  {
    id: '6',
    brand: 'Basic-Fit',
    logo: `https://img.logo.dev/basic-fit.com?token=${LOGO_TOKEN}`,
    discount: '1 mois',
    description: 'Offert sur abonnement',
    fullDescription: 'Votre premier mois d\'abonnement offert dans toutes les salles Basic-Fit. Accès illimité 24h/24 et 7j/7.',
    category: 'Sport',
    color: '#ff6600',
    validUntil: '30 Avril 2026',
    image: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&q=80',
  },
  {
    id: '20',
    brand: 'Maisons du Monde',
    logo: `https://img.logo.dev/maisonsdumonde.com?token=${LOGO_TOKEN}`,
    discount: '-20%',
    description: 'Déco & mobilier',
    fullDescription: '20% de réduction sur la décoration et le mobilier. Idéal pour meubler et décorer votre nouveau chez-vous.',
    category: 'Maison',
    color: '#000000',
    code: 'MDM20HOME',
    validUntil: '30 Juin 2026',
    image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80',
  },
  {
    id: '22',
    brand: 'Zalando',
    logo: `https://img.logo.dev/zalando.fr?token=${LOGO_TOKEN}`,
    discount: '-15%',
    description: 'Mode en ligne',
    fullDescription: '15% de réduction sur votre première commande Zalando. Plus de 2000 marques de mode disponibles.',
    category: 'Mode',
    color: '#ff6900',
    code: 'ZALANDO15',
    validUntil: '31 Décembre 2026',
    image: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=800&q=80',
  },
  {
    id: '42',
    brand: 'Disney+',
    logo: `https://img.logo.dev/disneyplus.com?token=${LOGO_TOKEN}`,
    discount: '1 mois',
    description: 'Offert sur abonnement',
    fullDescription: '1 mois offert sur votre abonnement Disney+. Disney, Pixar, Marvel, Star Wars et National Geographic.',
    category: 'Streaming',
    color: '#113ccf',
    validUntil: '31 Mai 2026',
    image: 'https://images.unsplash.com/photo-1640499900704-b00dd6a1103a?w=800&q=80',
  },
  {
    id: '11',
    brand: 'Decathlon',
    logo: `https://img.logo.dev/decathlon.fr?token=${LOGO_TOKEN}`,
    discount: '-15%',
    description: 'Articles de sport',
    fullDescription: '15% de réduction sur tout le magasin Decathlon. Équipement sportif, vêtements et accessoires pour tous les sports.',
    category: 'Sport',
    color: '#0082c3',
    code: 'SPORT15LOC',
    validUntil: '31 Mai 2026',
    image: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800&q=80',
  },
  {
    id: '52',
    brand: 'Airbnb',
    logo: `https://img.logo.dev/airbnb.com?token=${LOGO_TOKEN}`,
    discount: '-25€',
    description: '1ère réservation',
    fullDescription: '25€ offerts sur votre première réservation Airbnb. Logements uniques partout dans le monde.',
    category: 'Voyage',
    color: '#ff5a5f',
    code: 'AIRBNB25',
    validUntil: '31 Décembre 2026',
    image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80',
  },
  {
    id: '16',
    brand: 'Boulanger',
    logo: `https://img.logo.dev/boulanger.com?token=${LOGO_TOKEN}`,
    discount: '-10%',
    description: 'High-tech & électro',
    fullDescription: '10% de réduction sur tout le site Boulanger. TV, informatique, petit électroménager et plus encore.',
    category: 'High-Tech',
    color: '#e63312',
    code: 'BOUL10LOC',
    validUntil: '30 Avril 2026',
    image: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=800&q=80',
  },
  {
    id: '24',
    brand: 'Nocibé',
    logo: `https://img.logo.dev/nocibe.fr?token=${LOGO_TOKEN}`,
    discount: '-30%',
    description: '2ème parfum',
    fullDescription: '-30% sur le 2ème parfum acheté. Large sélection de grandes marques de parfumerie.',
    category: 'Beauté',
    color: '#e91e8c',
    code: 'NOCIBE30',
    validUntil: '14 Février 2026',
    image: 'https://images.unsplash.com/photo-1541643600914-78b084683601?w=800&q=80',
  },
  {
    id: '3',
    brand: 'Castorama',
    logo: `https://img.logo.dev/castorama.fr?token=${LOGO_TOKEN}`,
    discount: '-10%',
    description: 'Bricolage et jardinage',
    fullDescription: 'Réduction de 10% sur tous vos achats bricolage et jardinage. Idéal pour aménager votre nouveau logement. Offre valable en magasin.',
    category: 'Maison',
    color: '#0066cc',
    code: 'CASTO10LOC',
    validUntil: '30 Juin 2026',
    image: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800&q=80',
  },
  {
    id: '34',
    brand: 'HelloFresh',
    logo: `https://img.logo.dev/hellofresh.fr?token=${LOGO_TOKEN}`,
    discount: '-60€',
    description: 'Sur 4 premières box',
    fullDescription: '60€ de réduction répartis sur vos 4 premières box HelloFresh. Recettes et ingrédients frais livrés.',
    category: 'Food',
    color: '#91c11e',
    code: 'HELLO60',
    validUntil: '30 Juin 2026',
    image: 'https://images.unsplash.com/photo-1466637574441-749b8f19452f?w=800&q=80',
  },
  {
    id: '27',
    brand: 'Mango',
    logo: `https://img.logo.dev/mango.com?token=${LOGO_TOKEN}`,
    discount: '-25%',
    description: 'Collection printemps',
    fullDescription: '25% de réduction sur la collection printemps Mango. Mode femme et homme tendance.',
    category: 'Mode',
    color: '#000000',
    code: 'MANGO25',
    validUntil: '30 Avril 2026',
    image: 'https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=800&q=80',
  },
  {
    id: '60',
    brand: 'Doctolib',
    logo: `https://img.logo.dev/doctolib.fr?token=${LOGO_TOKEN}`,
    discount: 'Gratuit',
    description: 'Téléconsultation',
    fullDescription: 'Première téléconsultation offerte sur Doctolib. Médecins disponibles 24h/24.',
    category: 'Services',
    color: '#107aca',
    validUntil: '31 Décembre 2026',
    image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&q=80',
  },
  {
    id: '31',
    brand: 'Puma',
    logo: `https://img.logo.dev/puma.com?token=${LOGO_TOKEN}`,
    discount: '-20%',
    description: 'Running & lifestyle',
    fullDescription: '20% sur les collections running et lifestyle Puma. Chaussures et vêtements.',
    category: 'Sport',
    color: '#000000',
    code: 'PUMA20',
    validUntil: '30 Juin 2026',
    image: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=800&q=80',
  },
  {
    id: '38',
    brand: 'Samsung',
    logo: `https://img.logo.dev/samsung.com?token=${LOGO_TOKEN}`,
    discount: '-100€',
    description: 'Sur TV & smartphones',
    fullDescription: '100€ de réduction sur une sélection de TV et smartphones Samsung. Offre exclusive locataires.',
    category: 'High-Tech',
    color: '#1428a0',
    code: 'SAMSUNG100',
    validUntil: '31 Mai 2026',
    image: 'https://images.unsplash.com/photo-1585060544812-6b45742d762f?w=800&q=80',
  },
  {
    id: '49',
    brand: 'UGC',
    logo: `https://img.logo.dev/ugc.fr?token=${LOGO_TOKEN}`,
    discount: '1 place',
    description: 'Offerte',
    fullDescription: '1 place de cinéma offerte pour tout nouvel abonnement UGC Illimité souscrit.',
    category: 'Culture',
    color: '#c8102e',
    validUntil: '30 Juin 2026',
    image: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800&q=80',
  },
  {
    id: '23',
    brand: 'Conforama',
    logo: `https://img.logo.dev/conforama.fr?token=${LOGO_TOKEN}`,
    discount: '-100€',
    description: 'Dès 500€ d\'achat',
    fullDescription: '100€ de réduction dès 500€ d\'achat. Meubles, literie, électroménager pour équiper votre logement.',
    category: 'Maison',
    color: '#e4002b',
    code: 'CONFO100',
    validUntil: '30 Avril 2026',
    image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80',
  },
  {
    id: '39',
    brand: 'Yves Rocher',
    logo: `https://img.logo.dev/yves-rocher.fr?token=${LOGO_TOKEN}`,
    discount: '-40%',
    description: '2ème produit',
    fullDescription: '-40% sur le 2ème produit acheté. Cosmétiques naturels et soins botaniques.',
    category: 'Beauté',
    color: '#006633',
    code: 'YVES40',
    validUntil: '30 Avril 2026',
    image: 'https://images.unsplash.com/photo-1571875257727-256c39da42af?w=800&q=80',
  },
  {
    id: '53',
    brand: 'SNCF Connect',
    logo: `https://img.logo.dev/sncf-connect.com?token=${LOGO_TOKEN}`,
    discount: '-15€',
    description: 'Dès 50€ d\'achat',
    fullDescription: '15€ de réduction dès 50€ d\'achat sur SNCF Connect. TGV, Intercités et TER.',
    category: 'Voyage',
    color: '#82be00',
    code: 'SNCF15',
    validUntil: '30 Juin 2026',
    image: 'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=800&q=80',
  },
  {
    id: '45',
    brand: 'Auchan',
    logo: `https://img.logo.dev/auchan.fr?token=${LOGO_TOKEN}`,
    discount: '-10€',
    description: 'Dès 80€ de courses',
    fullDescription: '10€ offerts dès 80€ de courses sur Auchan Drive. Alimentaire et produits du quotidien.',
    category: 'Courses',
    color: '#e30613',
    code: 'AUCHAN10',
    validUntil: '31 Décembre 2026',
    image: 'https://images.unsplash.com/photo-1534723452862-4c874018d66d?w=800&q=80',
  },
  {
    id: '28',
    brand: 'Uniqlo',
    logo: `https://img.logo.dev/uniqlo.com?token=${LOGO_TOKEN}`,
    discount: '-10%',
    description: 'Basics essentiels',
    fullDescription: '10% sur les essentiels Uniqlo. T-shirts, jeans et vêtements du quotidien de qualité.',
    category: 'Mode',
    color: '#ff0000',
    code: 'UNIQLO10',
    validUntil: '31 Mai 2026',
    image: 'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=800&q=80',
  },
  {
    id: '43',
    brand: 'Canal+',
    logo: `https://img.logo.dev/canalplus.com?token=${LOGO_TOKEN}`,
    discount: '-50%',
    description: '6 premiers mois',
    fullDescription: '-50% sur les 6 premiers mois d\'abonnement Canal+. Sport, cinéma et séries.',
    category: 'Streaming',
    color: '#000000',
    code: 'CANAL50',
    validUntil: '30 Juin 2026',
    image: 'https://images.unsplash.com/photo-1522869635100-9f4c5e86aa37?w=800&q=80',
  },
  {
    id: '21',
    brand: 'Picard',
    logo: `https://img.logo.dev/picard.fr?token=${LOGO_TOKEN}`,
    discount: '-10€',
    description: 'Dès 50€ d\'achat',
    fullDescription: '10€ de réduction dès 50€ d\'achat chez Picard. Surgelés de qualité pour des repas faciles et savoureux.',
    category: 'Food',
    color: '#003d7c',
    code: 'PICARD10',
    validUntil: '31 Mars 2026',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
  },
  {
    id: '25',
    brand: 'But',
    logo: `https://img.logo.dev/but.fr?token=${LOGO_TOKEN}`,
    discount: '-15%',
    description: 'Meubles & déco',
    fullDescription: '15% de réduction sur tout le mobilier et la décoration But. Canapés, lits, rangements et accessoires.',
    category: 'Maison',
    color: '#e30613',
    code: 'BUT15LOC',
    validUntil: '31 Mai 2026',
    image: 'https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=800&q=80',
  },
  {
    id: '59',
    brand: 'Luko',
    logo: `https://img.logo.dev/luko.eu?token=${LOGO_TOKEN}`,
    discount: '2 mois',
    description: 'Assurance offerte',
    fullDescription: '2 mois d\'assurance habitation offerts chez Luko. Couverture complète et remboursement rapide.',
    category: 'Services',
    color: '#ff6b6b',
    validUntil: '31 Décembre 2026',
    image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&q=80',
  },
  {
    id: '36',
    brand: 'Cdiscount',
    logo: `https://img.logo.dev/cdiscount.com?token=${LOGO_TOKEN}`,
    discount: '-15€',
    description: 'Dès 99€ d\'achat',
    fullDescription: '15€ de réduction dès 99€ d\'achat sur Cdiscount. High-tech, électroménager et maison.',
    category: 'High-Tech',
    color: '#e30613',
    code: 'CDIS15',
    validUntil: '30 Juin 2026',
    image: 'https://images.unsplash.com/photo-1550009158-9ebf69173e03?w=800&q=80',
  },
  {
    id: '29',
    brand: 'Celio',
    logo: `https://img.logo.dev/celio.com?token=${LOGO_TOKEN}`,
    discount: '-20%',
    description: 'Mode homme',
    fullDescription: '20% de réduction sur toute la collection homme Celio. Du casual au chic.',
    category: 'Mode',
    color: '#1a1a1a',
    code: 'CELIO20',
    validUntil: '30 Juin 2026',
    image: 'https://images.unsplash.com/photo-1490578474895-699cd4e2cf59?w=800&q=80',
  },
  {
    id: '32',
    brand: 'Fitness Park',
    logo: `https://img.logo.dev/fitnesspark.fr?token=${LOGO_TOKEN}`,
    discount: '2 mois',
    description: 'Offerts sur 12 mois',
    fullDescription: '2 mois offerts sur un abonnement 12 mois Fitness Park. Accès à toutes les salles de France.',
    category: 'Sport',
    color: '#ff0000',
    validUntil: '31 Mai 2026',
    image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800&q=80',
  },
  {
    id: '40',
    brand: 'Marionnaud',
    logo: `https://img.logo.dev/marionnaud.fr?token=${LOGO_TOKEN}`,
    discount: '-20%',
    description: 'Tout le magasin',
    fullDescription: '20% de réduction sur tout le magasin Marionnaud. Parfums, maquillage et soins.',
    category: 'Beauté',
    color: '#d4145a',
    code: 'MARIO20',
    validUntil: '31 Mai 2026',
    image: 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=800&q=80',
  },
  {
    id: '33',
    brand: 'Just Eat',
    logo: `https://img.logo.dev/just-eat.fr?token=${LOGO_TOKEN}`,
    discount: '-7€',
    description: 'Première commande',
    fullDescription: '7€ offerts sur votre première commande Just Eat. Des milliers de restaurants à portée de clic.',
    category: 'Food',
    color: '#ff8000',
    code: 'JUSTEAT7',
    validUntil: '31 Décembre 2026',
    image: 'https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?w=800&q=80',
  },
  {
    id: '26',
    brand: 'Habitat',
    logo: `https://img.logo.dev/habitat.fr?token=${LOGO_TOKEN}`,
    discount: '-20%',
    description: 'Design contemporain',
    fullDescription: '20% sur le mobilier design Habitat. Créez un intérieur unique avec des pièces contemporaines.',
    category: 'Maison',
    color: '#000000',
    code: 'HABITAT20',
    validUntil: '30 Juin 2026',
    image: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=800&q=80',
  },
  {
    id: '54',
    brand: 'BlaBlaCar',
    logo: `https://img.logo.dev/blablacar.fr?token=${LOGO_TOKEN}`,
    discount: '-5€',
    description: '1er trajet',
    fullDescription: '5€ offerts sur votre premier trajet BlaBlaCar. Covoiturage économique et écologique.',
    category: 'Voyage',
    color: '#00aaff',
    code: 'BLABLA5',
    validUntil: '31 Décembre 2026',
    image: 'https://images.unsplash.com/photo-1449965408869-ebd3fee56ce8?w=800&q=80',
  },
  {
    id: '48',
    brand: 'Cultura',
    logo: `https://img.logo.dev/cultura.com?token=${LOGO_TOKEN}`,
    discount: '-15%',
    description: 'Livres & loisirs créatifs',
    fullDescription: '15% de réduction sur les livres et loisirs créatifs Cultura. Papeterie incluse.',
    category: 'Culture',
    color: '#e30044',
    code: 'CULTURA15',
    validUntil: '31 Mai 2026',
    image: 'https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=800&q=80',
  },
  {
    id: '44',
    brand: 'Deezer',
    logo: `https://img.logo.dev/deezer.com?token=${LOGO_TOKEN}`,
    discount: '2 mois',
    description: 'Premium offert',
    fullDescription: '2 mois de Deezer Premium offerts. 90 millions de titres sans publicité.',
    category: 'Streaming',
    color: '#feaa2d',
    validUntil: '31 Août 2026',
    image: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&q=80',
  },
  {
    id: '30',
    brand: 'Jules',
    logo: `https://img.logo.dev/jules.com?token=${LOGO_TOKEN}`,
    discount: '-15%',
    description: 'Vêtements homme',
    fullDescription: '15% sur la mode masculine Jules. Chemises, pantalons, vestes et accessoires.',
    category: 'Mode',
    color: '#003366',
    code: 'JULES15',
    validUntil: '31 Mai 2026',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80',
  },
  {
    id: '37',
    brand: 'Fnac',
    logo: `https://img.logo.dev/fnac.com?token=${LOGO_TOKEN}`,
    discount: '-10%',
    description: 'High-tech & culture',
    fullDescription: '10% de réduction sur le high-tech et les produits culturels Fnac. TV, audio, livres et plus.',
    category: 'High-Tech',
    color: '#e1a400',
    code: 'FNAC10LOC',
    validUntil: '15 Mai 2026',
    image: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800&q=80',
  },
  {
    id: '35',
    brand: 'Frichti',
    logo: `https://img.logo.dev/frichti.co?token=${LOGO_TOKEN}`,
    discount: '-10€',
    description: 'Dès 25€ d\'achat',
    fullDescription: '10€ offerts dès 25€ d\'achat sur Frichti. Plats cuisinés frais et produits du quotidien.',
    category: 'Food',
    color: '#00b67a',
    code: 'FRICHTI10',
    validUntil: '31 Mai 2026',
    image: 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?w=800&q=80',
  },
  {
    id: '41',
    brand: 'The Body Shop',
    logo: `https://img.logo.dev/thebodyshop.com?token=${LOGO_TOKEN}`,
    discount: '-25%',
    description: 'Soins corps & visage',
    fullDescription: '25% sur les soins corps et visage The Body Shop. Produits naturels et éthiques.',
    category: 'Beauté',
    color: '#004225',
    code: 'BODY25',
    validUntil: '30 Juin 2026',
    image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&q=80',
  },
  {
    id: '46',
    brand: 'Leclerc',
    logo: `https://img.logo.dev/e-leclerc.com?token=${LOGO_TOKEN}`,
    discount: '-5%',
    description: 'Drive & livraison',
    fullDescription: '5% de réduction sur vos commandes Leclerc Drive ou livraison à domicile.',
    category: 'Courses',
    color: '#0066b3',
    code: 'LECLERC5',
    validUntil: '31 Décembre 2026',
    image: 'https://images.unsplash.com/photo-1604719312566-8912e9227c6a?w=800&q=80',
  },
  {
    id: '55',
    brand: 'Europcar',
    logo: `https://img.logo.dev/europcar.fr?token=${LOGO_TOKEN}`,
    discount: '-20%',
    description: 'Location véhicule',
    fullDescription: '20% de réduction sur votre location de véhicule Europcar. Voitures et utilitaires.',
    category: 'Voyage',
    color: '#006633',
    code: 'EURO20',
    validUntil: '30 Septembre 2026',
    image: 'https://images.unsplash.com/photo-1485291571150-772bcfc10da5?w=800&q=80',
  },
  {
    id: '57',
    brand: 'Helpling',
    logo: `https://img.logo.dev/helpling.fr?token=${LOGO_TOKEN}`,
    discount: '-20€',
    description: '1ère réservation',
    fullDescription: '20€ offerts sur votre première réservation Helpling. Ménage et repassage à domicile.',
    category: 'Services',
    color: '#00b5e2',
    code: 'HELP20',
    validUntil: '30 Juin 2026',
    image: 'https://images.unsplash.com/photo-1527515545081-5db817172677?w=800&q=80',
  },
  {
    id: '50',
    brand: 'Pathé Gaumont',
    logo: `https://img.logo.dev/pathe.fr?token=${LOGO_TOKEN}`,
    discount: '-20%',
    description: 'Carte CinéPass',
    fullDescription: '20% de réduction sur votre abonnement CinéPass Pathé Gaumont le premier mois.',
    category: 'Culture',
    color: '#ffc300',
    code: 'CINE20',
    validUntil: '31 Mai 2026',
    image: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=800&q=80',
  },
  {
    id: '47',
    brand: 'Intermarché',
    logo: `https://img.logo.dev/intermarche.com?token=${LOGO_TOKEN}`,
    discount: '-10€',
    description: 'Dès 70€ d\'achat',
    fullDescription: '10€ de réduction dès 70€ d\'achat en drive ou livraison Intermarché.',
    category: 'Courses',
    color: '#e30613',
    code: 'INTER10',
    validUntil: '30 Juin 2026',
    image: 'https://images.unsplash.com/photo-1579113800032-c38bd7635818?w=800&q=80',
  },
  {
    id: '58',
    brand: 'Stuart',
    logo: `https://img.logo.dev/stuart.com?token=${LOGO_TOKEN}`,
    discount: '-10€',
    description: 'Livraison express',
    fullDescription: '10€ offerts sur votre première livraison express Stuart. Colis et courses livrés en 1h.',
    category: 'Services',
    color: '#5c2d91',
    code: 'STUART10',
    validUntil: '31 Mai 2026',
    image: 'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=800&q=80',
  },
];
  {
    id: '6',
    brand: 'Basic-Fit',
    logo: `https://img.logo.dev/basic-fit.com?token=${LOGO_TOKEN}`,
    discount: '1 mois',
    description: 'Offert sur abonnement',
    fullDescription: 'Votre premier mois d\'abonnement offert dans toutes les salles Basic-Fit. Accès illimité 24h/24 et 7j/7.',
    category: 'Sport',
    color: '#ff6600',
    validUntil: '30 Avril 2026',
    image: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&q=80',
  },
  {
    id: '11',
    brand: 'Decathlon',
    logo: `https://img.logo.dev/decathlon.fr?token=${LOGO_TOKEN}`,
    discount: '-15%',
    description: 'Articles de sport',
    fullDescription: '15% de réduction sur tout le magasin Decathlon. Équipement sportif, vêtements et accessoires pour tous les sports.',
    category: 'Sport',
    color: '#0082c3',
    code: 'SPORT15LOC',
    validUntil: '31 Mai 2026',
    image: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800&q=80',
  },
  {
    id: '18',
    brand: 'Nike',
    logo: `https://img.logo.dev/nike.com?token=${LOGO_TOKEN}`,
    discount: '-25%',
    description: 'Membres exclusif',
    fullDescription: '25% de réduction pour les nouveaux membres Nike. Chaussures, vêtements et équipements sportifs.',
    category: 'Sport',
    color: '#000000',
    code: 'NIKE25NEW',
    validUntil: '31 Mai 2026',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80',
  },
  {
    id: '31',
    brand: 'Puma',
    logo: `https://img.logo.dev/puma.com?token=${LOGO_TOKEN}`,
    discount: '-20%',
    description: 'Running & lifestyle',
    fullDescription: '20% sur les collections running et lifestyle Puma. Chaussures et vêtements.',
    category: 'Sport',
    color: '#000000',
    code: 'PUMA20',
    validUntil: '30 Juin 2026',
    image: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=800&q=80',
  },
  {
    id: '32',
    brand: 'Fitness Park',
    logo: `https://img.logo.dev/fitnesspark.fr?token=${LOGO_TOKEN}`,
    discount: '2 mois',
    description: 'Offerts sur 12 mois',
    fullDescription: '2 mois offerts sur un abonnement 12 mois Fitness Park. Accès à toutes les salles de France.',
    category: 'Sport',
    color: '#ff0000',
    validUntil: '31 Mai 2026',
    image: 'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800&q=80',
  },

  // ========== FOOD ==========
  {
    id: '5',
    brand: 'Uber Eats',
    logo: `https://img.logo.dev/ubereats.com?token=${LOGO_TOKEN}`,
    discount: '-5€',
    description: 'Première commande',
    fullDescription: '5€ offerts sur votre première commande Uber Eats. Faites-vous livrer vos plats préférés directement chez vous.',
    category: 'Food',
    color: '#06c167',
    code: 'BIENVENUE5',
    validUntil: '31 Décembre 2026',
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&q=80',
  },
  {
    id: '12',
    brand: 'Deliveroo',
    logo: `https://img.logo.dev/deliveroo.fr?token=${LOGO_TOKEN}`,
    discount: '-30%',
    description: '3 premières commandes',
    fullDescription: '30% de réduction sur vos 3 premières commandes Deliveroo. Découvrez les meilleurs restaurants de votre quartier.',
    category: 'Food',
    color: '#00ccbc',
    code: 'NEW30',
    validUntil: '31 Décembre 2026',
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80',
  },
  {
    id: '21',
    brand: 'Picard',
    logo: `https://img.logo.dev/picard.fr?token=${LOGO_TOKEN}`,
    discount: '-10€',
    description: 'Dès 50€ d\'achat',
    fullDescription: '10€ de réduction dès 50€ d\'achat chez Picard. Surgelés de qualité pour des repas faciles et savoureux.',
    category: 'Food',
    color: '#003d7c',
    code: 'PICARD10',
    validUntil: '31 Mars 2026',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
  },
  {
    id: '33',
    brand: 'Just Eat',
    logo: `https://img.logo.dev/just-eat.fr?token=${LOGO_TOKEN}`,
    discount: '-7€',
    description: 'Première commande',
    fullDescription: '7€ offerts sur votre première commande Just Eat. Des milliers de restaurants à portée de clic.',
    category: 'Food',
    color: '#ff8000',
    code: 'JUSTEAT7',
    validUntil: '31 Décembre 2026',
    image: 'https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?w=800&q=80',
  },
  {
    id: '34',
    brand: 'HelloFresh',
    logo: `https://img.logo.dev/hellofresh.fr?token=${LOGO_TOKEN}`,
    discount: '-60€',
    description: 'Sur 4 premières box',
    fullDescription: '60€ de réduction répartis sur vos 4 premières box HelloFresh. Recettes et ingrédients frais livrés.',
    category: 'Food',
    color: '#91c11e',
    code: 'HELLO60',
    validUntil: '30 Juin 2026',
    image: 'https://images.unsplash.com/photo-1466637574441-749b8f19452f?w=800&q=80',
  },
  {
    id: '35',
    brand: 'Frichti',
    logo: `https://img.logo.dev/frichti.co?token=${LOGO_TOKEN}`,
    discount: '-10€',
    description: 'Dès 25€ d\'achat',
    fullDescription: '10€ offerts dès 25€ d\'achat sur Frichti. Plats cuisinés frais et produits du quotidien.',
    category: 'Food',
    color: '#00b67a',
    code: 'FRICHTI10',
    validUntil: '31 Mai 2026',
    image: 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?w=800&q=80',
  },

  // ========== HIGH-TECH ==========
  {
    id: '4',
    brand: 'Darty',
    logo: `https://img.logo.dev/darty.com?token=${LOGO_TOKEN}`,
    discount: '-15%',
    description: 'Électroménager',
    fullDescription: 'Équipez votre logement avec 15% de réduction sur tout l\'électroménager : réfrigérateur, lave-linge, four, aspirateur et plus encore.',
    category: 'High-Tech',
    color: '#e30613',
    code: 'DARTY15NEW',
    validUntil: '28 Février 2026',
    image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80',
  },
  {
    id: '16',
    brand: 'Boulanger',
    logo: `https://img.logo.dev/boulanger.com?token=${LOGO_TOKEN}`,
    discount: '-10%',
    description: 'High-tech & électro',
    fullDescription: '10% de réduction sur tout le site Boulanger. TV, informatique, petit électroménager et plus encore.',
    category: 'High-Tech',
    color: '#e63312',
    code: 'BOUL10LOC',
    validUntil: '30 Avril 2026',
    image: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=800&q=80',
  },
  {
    id: '9',
    brand: 'Amazon',
    logo: `https://img.logo.dev/amazon.fr?token=${LOGO_TOKEN}`,
    discount: '-10€',
    description: 'Sur votre 1ère commande',
    fullDescription: '10€ de réduction sur votre première commande Amazon de 50€ minimum. Livraison gratuite incluse.',
    category: 'High-Tech',
    color: '#ff9900',
    code: 'NEWLOC10',
    validUntil: '31 Décembre 2026',
    image: 'https://images.unsplash.com/photo-1523474253046-8cd2748b5fd2?w=800&q=80',
  },
  {
    id: '36',
    brand: 'Cdiscount',
    logo: `https://img.logo.dev/cdiscount.com?token=${LOGO_TOKEN}`,
    discount: '-15€',
    description: 'Dès 99€ d\'achat',
    fullDescription: '15€ de réduction dès 99€ d\'achat sur Cdiscount. High-tech, électroménager et maison.',
    category: 'High-Tech',
    color: '#e30613',
    code: 'CDIS15',
    validUntil: '30 Juin 2026',
    image: 'https://images.unsplash.com/photo-1550009158-9ebf69173e03?w=800&q=80',
  },
  {
    id: '37',
    brand: 'Fnac',
    logo: `https://img.logo.dev/fnac.com?token=${LOGO_TOKEN}`,
    discount: '-10%',
    description: 'High-tech & culture',
    fullDescription: '10% de réduction sur le high-tech et les produits culturels Fnac. TV, audio, livres et plus.',
    category: 'High-Tech',
    color: '#e1a400',
    code: 'FNAC10LOC',
    validUntil: '15 Mai 2026',
    image: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800&q=80',
  },
  {
    id: '38',
    brand: 'Samsung',
    logo: `https://img.logo.dev/samsung.com?token=${LOGO_TOKEN}`,
    discount: '-100€',
    description: 'Sur TV & smartphones',
    fullDescription: '100€ de réduction sur une sélection de TV et smartphones Samsung. Offre exclusive locataires.',
    category: 'High-Tech',
    color: '#1428a0',
    code: 'SAMSUNG100',
    validUntil: '31 Mai 2026',
    image: 'https://images.unsplash.com/photo-1585060544812-6b45742d762f?w=800&q=80',
  },

  // ========== BEAUTÉ ==========
  {
    id: '15',
    brand: 'Sephora',
    logo: `https://img.logo.dev/sephora.fr?token=${LOGO_TOKEN}`,
    discount: '-25%',
    description: 'Beauté et parfums',
    fullDescription: '25% de réduction sur une sélection de produits beauté et parfums. Maquillage, soins et coffrets inclus.',
    category: 'Beauté',
    color: '#000000',
    code: 'BEAUTY25',
    validUntil: '28 Février 2026',
    image: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=800&q=80',
  },
  {
    id: '24',
    brand: 'Nocibé',
    logo: `https://img.logo.dev/nocibe.fr?token=${LOGO_TOKEN}`,
    discount: '-30%',
    description: '2ème parfum',
    fullDescription: '-30% sur le 2ème parfum acheté. Large sélection de grandes marques de parfumerie.',
    category: 'Beauté',
    color: '#e91e8c',
    code: 'NOCIBE30',
    validUntil: '14 Février 2026',
    image: 'https://images.unsplash.com/photo-1541643600914-78b084683601?w=800&q=80',
  },
  {
    id: '39',
    brand: 'Yves Rocher',
    logo: `https://img.logo.dev/yves-rocher.fr?token=${LOGO_TOKEN}`,
    discount: '-40%',
    description: '2ème produit',
    fullDescription: '-40% sur le 2ème produit acheté. Cosmétiques naturels et soins botaniques.',
    category: 'Beauté',
    color: '#006633',
    code: 'YVES40',
    validUntil: '30 Avril 2026',
    image: 'https://images.unsplash.com/photo-1571875257727-256c39da42af?w=800&q=80',
  },
  {
    id: '40',
    brand: 'Marionnaud',
    logo: `https://img.logo.dev/marionnaud.fr?token=${LOGO_TOKEN}`,
    discount: '-20%',
    description: 'Tout le magasin',
    fullDescription: '20% de réduction sur tout le magasin Marionnaud. Parfums, maquillage et soins.',
    category: 'Beauté',
    color: '#d4145a',
    code: 'MARIO20',
    validUntil: '31 Mai 2026',
    image: 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=800&q=80',
  },
  {
    id: '41',
    brand: 'The Body Shop',
    logo: `https://img.logo.dev/thebodyshop.com?token=${LOGO_TOKEN}`,
    discount: '-25%',
    description: 'Soins corps & visage',
    fullDescription: '25% sur les soins corps et visage The Body Shop. Produits naturels et éthiques.',
    category: 'Beauté',
    color: '#004225',
    code: 'BODY25',
    validUntil: '30 Juin 2026',
    image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&q=80',
  },

  // ========== STREAMING ==========
  {
    id: '10',
    brand: 'Netflix',
    logo: `https://img.logo.dev/netflix.com?token=${LOGO_TOKEN}`,
    discount: '2 mois',
    description: 'Offerts sur abonnement',
    fullDescription: 'Profitez de 2 mois offerts sur votre nouvel abonnement Netflix. Films, séries et documentaires en illimité.',
    category: 'Streaming',
    color: '#e50914',
    validUntil: '30 Juin 2026',
    image: 'https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?w=800&q=80',
  },
  {
    id: '13',
    brand: 'Spotify',
    logo: `https://img.logo.dev/spotify.com?token=${LOGO_TOKEN}`,
    discount: '3 mois',
    description: 'Premium offert',
    fullDescription: '3 mois de Spotify Premium offerts. Musique illimitée sans pub, mode hors connexion et qualité audio supérieure.',
    category: 'Streaming',
    color: '#1db954',
    validUntil: '30 Septembre 2026',
    image: 'https://images.unsplash.com/photo-1611339555312-e607c8352fd7?w=800&q=80',
  },
  {
    id: '42',
    brand: 'Disney+',
    logo: `https://img.logo.dev/disneyplus.com?token=${LOGO_TOKEN}`,
    discount: '1 mois',
    description: 'Offert sur abonnement',
    fullDescription: '1 mois offert sur votre abonnement Disney+. Disney, Pixar, Marvel, Star Wars et National Geographic.',
    category: 'Streaming',
    color: '#113ccf',
    validUntil: '31 Mai 2026',
    image: 'https://images.unsplash.com/photo-1640499900704-b00dd6a1103a?w=800&q=80',
  },
  {
    id: '43',
    brand: 'Canal+',
    logo: `https://img.logo.dev/canalplus.com?token=${LOGO_TOKEN}`,
    discount: '-50%',
    description: '6 premiers mois',
    fullDescription: '-50% sur les 6 premiers mois d\'abonnement Canal+. Sport, cinéma et séries.',
    category: 'Streaming',
    color: '#000000',
    code: 'CANAL50',
    validUntil: '30 Juin 2026',
    image: 'https://images.unsplash.com/photo-1522869635100-9f4c5e86aa37?w=800&q=80',
  },
  {
    id: '44',
    brand: 'Deezer',
    logo: `https://img.logo.dev/deezer.com?token=${LOGO_TOKEN}`,
    discount: '2 mois',
    description: 'Premium offert',
    fullDescription: '2 mois de Deezer Premium offerts. 90 millions de titres sans publicité.',
    category: 'Streaming',
    color: '#feaa2d',
    validUntil: '31 Août 2026',
    image: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&q=80',
  },

  // ========== COURSES ==========
  {
    id: '17',
    brand: 'Carrefour',
    logo: `https://img.logo.dev/carrefour.fr?token=${LOGO_TOKEN}`,
    discount: '-8%',
    description: 'Courses alimentaires',
    fullDescription: '8% de réduction sur vos courses en ligne Carrefour. Livraison à domicile ou retrait en drive.',
    category: 'Courses',
    color: '#004e9f',
    code: 'COURSES8',
    validUntil: '31 Décembre 2026',
    image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=800&q=80',
  },
  {
    id: '45',
    brand: 'Auchan',
    logo: `https://img.logo.dev/auchan.fr?token=${LOGO_TOKEN}`,
    discount: '-10€',
    description: 'Dès 80€ de courses',
    fullDescription: '10€ offerts dès 80€ de courses sur Auchan Drive. Alimentaire et produits du quotidien.',
    category: 'Courses',
    color: '#e30613',
    code: 'AUCHAN10',
    validUntil: '31 Décembre 2026',
    image: 'https://images.unsplash.com/photo-1534723452862-4c874018d66d?w=800&q=80',
  },
  {
    id: '46',
    brand: 'Leclerc',
    logo: `https://img.logo.dev/e-leclerc.com?token=${LOGO_TOKEN}`,
    discount: '-5%',
    description: 'Drive & livraison',
    fullDescription: '5% de réduction sur vos commandes Leclerc Drive ou livraison à domicile.',
    category: 'Courses',
    color: '#0066b3',
    code: 'LECLERC5',
    validUntil: '31 Décembre 2026',
    image: 'https://images.unsplash.com/photo-1604719312566-8912e9227c6a?w=800&q=80',
  },
  {
    id: '47',
    brand: 'Intermarché',
    logo: `https://img.logo.dev/intermarche.com?token=${LOGO_TOKEN}`,
    discount: '-10€',
    description: 'Dès 70€ d\'achat',
    fullDescription: '10€ de réduction dès 70€ d\'achat en drive ou livraison Intermarché.',
    category: 'Courses',
    color: '#e30613',
    code: 'INTER10',
    validUntil: '30 Juin 2026',
    image: 'https://images.unsplash.com/photo-1579113800032-c38bd7635818?w=800&q=80',
  },

  // ========== CULTURE ==========
  {
    id: '7',
    brand: 'Fnac',
    logo: `https://img.logo.dev/fnac.com?token=${LOGO_TOKEN}`,
    discount: '-10%',
    description: 'Livres et multimédia',
    fullDescription: '10% de réduction sur les livres, CD, vinyles et produits multimédia. Carte Fnac non requise pour cette offre.',
    category: 'Culture',
    color: '#e1a400',
    code: 'FNAC10LOC',
    validUntil: '15 Mai 2026',
    image: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800&q=80',
  },
  {
    id: '48',
    brand: 'Cultura',
    logo: `https://img.logo.dev/cultura.com?token=${LOGO_TOKEN}`,
    discount: '-15%',
    description: 'Livres & loisirs créatifs',
    fullDescription: '15% de réduction sur les livres et loisirs créatifs Cultura. Papeterie incluse.',
    category: 'Culture',
    color: '#e30044',
    code: 'CULTURA15',
    validUntil: '31 Mai 2026',
    image: 'https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=800&q=80',
  },
  {
    id: '49',
    brand: 'UGC',
    logo: `https://img.logo.dev/ugc.fr?token=${LOGO_TOKEN}`,
    discount: '1 place',
    description: 'Offerte',
    fullDescription: '1 place de cinéma offerte pour tout nouvel abonnement UGC Illimité souscrit.',
    category: 'Culture',
    color: '#c8102e',
    validUntil: '30 Juin 2026',
    image: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800&q=80',
  },
  {
    id: '50',
    brand: 'Pathé Gaumont',
    logo: `https://img.logo.dev/pathe.fr?token=${LOGO_TOKEN}`,
    discount: '-20%',
    description: 'Carte CinéPass',
    fullDescription: '20% de réduction sur votre abonnement CinéPass Pathé Gaumont le premier mois.',
    category: 'Culture',
    color: '#ffc300',
    code: 'CINE20',
    validUntil: '31 Mai 2026',
    image: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=800&q=80',
  },

  // ========== VOYAGE ==========
  {
    id: '51',
    brand: 'Booking.com',
    logo: `https://img.logo.dev/booking.com?token=${LOGO_TOKEN}`,
    discount: '-10%',
    description: 'Hébergements',
    fullDescription: '10% de réduction sur une sélection d\'hébergements Booking.com. Hôtels, appartements et maisons.',
    category: 'Voyage',
    color: '#003580',
    code: 'BOOK10LOC',
    validUntil: '31 Décembre 2026',
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
  },
  {
    id: '52',
    brand: 'Airbnb',
    logo: `https://img.logo.dev/airbnb.com?token=${LOGO_TOKEN}`,
    discount: '-25€',
    description: '1ère réservation',
    fullDescription: '25€ offerts sur votre première réservation Airbnb. Logements uniques partout dans le monde.',
    category: 'Voyage',
    color: '#ff5a5f',
    code: 'AIRBNB25',
    validUntil: '31 Décembre 2026',
    image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80',
  },
  {
    id: '53',
    brand: 'SNCF Connect',
    logo: `https://img.logo.dev/sncf-connect.com?token=${LOGO_TOKEN}`,
    discount: '-15€',
    description: 'Dès 50€ d\'achat',
    fullDescription: '15€ de réduction dès 50€ d\'achat sur SNCF Connect. TGV, Intercités et TER.',
    category: 'Voyage',
    color: '#82be00',
    code: 'SNCF15',
    validUntil: '30 Juin 2026',
    image: 'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=800&q=80',
  },
  {
    id: '54',
    brand: 'BlaBlaCar',
    logo: `https://img.logo.dev/blablacar.fr?token=${LOGO_TOKEN}`,
    discount: '-5€',
    description: '1er trajet',
    fullDescription: '5€ offerts sur votre premier trajet BlaBlaCar. Covoiturage économique et écologique.',
    category: 'Voyage',
    color: '#00aaff',
    code: 'BLABLA5',
    validUntil: '31 Décembre 2026',
    image: 'https://images.unsplash.com/photo-1449965408869-ebd3fee56ce8?w=800&q=80',
  },
  {
    id: '55',
    brand: 'Europcar',
    logo: `https://img.logo.dev/europcar.fr?token=${LOGO_TOKEN}`,
    discount: '-20%',
    description: 'Location véhicule',
    fullDescription: '20% de réduction sur votre location de véhicule Europcar. Voitures et utilitaires.',
    category: 'Voyage',
    color: '#006633',
    code: 'EURO20',
    validUntil: '30 Septembre 2026',
    image: 'https://images.unsplash.com/photo-1485291571150-772bcfc10da5?w=800&q=80',
  },

  // ========== SERVICES ==========
  {
    id: '56',
    brand: 'Wecasa',
    logo: `https://img.logo.dev/wecasa.fr?token=${LOGO_TOKEN}`,
    discount: '-15€',
    description: 'Ménage à domicile',
    fullDescription: '15€ offerts sur votre première prestation de ménage Wecasa. Professionnels certifiés.',
    category: 'Services',
    color: '#00d4aa',
    code: 'WECASA15',
    validUntil: '31 Décembre 2026',
    image: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800&q=80',
  },
  {
    id: '57',
    brand: 'Helpling',
    logo: `https://img.logo.dev/helpling.fr?token=${LOGO_TOKEN}`,
    discount: '-20€',
    description: '1ère réservation',
    fullDescription: '20€ offerts sur votre première réservation Helpling. Ménage et repassage à domicile.',
    category: 'Services',
    color: '#00b5e2',
    code: 'HELP20',
    validUntil: '30 Juin 2026',
    image: 'https://images.unsplash.com/photo-1527515545081-5db817172677?w=800&q=80',
  },
  {
    id: '58',
    brand: 'Stuart',
    logo: `https://img.logo.dev/stuart.com?token=${LOGO_TOKEN}`,
    discount: '-10€',
    description: 'Livraison express',
    fullDescription: '10€ offerts sur votre première livraison express Stuart. Colis et courses livrés en 1h.',
    category: 'Services',
    color: '#5c2d91',
    code: 'STUART10',
    validUntil: '31 Mai 2026',
    image: 'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=800&q=80',
  },
  {
    id: '59',
    brand: 'Luko',
    logo: `https://img.logo.dev/luko.eu?token=${LOGO_TOKEN}`,
    discount: '2 mois',
    description: 'Assurance offerte',
    fullDescription: '2 mois d\'assurance habitation offerts chez Luko. Couverture complète et remboursement rapide.',
    category: 'Services',
    color: '#ff6b6b',
    validUntil: '31 Décembre 2026',
    image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&q=80',
  },
  {
    id: '60',
    brand: 'Doctolib',
    logo: `https://img.logo.dev/doctolib.fr?token=${LOGO_TOKEN}`,
    discount: 'Gratuit',
    description: 'Téléconsultation',
    fullDescription: 'Première téléconsultation offerte sur Doctolib. Médecins disponibles 24h/24.',
    category: 'Services',
    color: '#107aca',
    validUntil: '31 Décembre 2026',
    image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&q=80',
  },
];

export const contracts: Contract[] = [
  {
    id: '1',
    provider: 'EDF',
    type: 'Énergie',
    category: 'energy',
    status: 'active',
    price: '85€/mois',
    nextDate: '15 Mars 2026',
    icon: 'Zap',
    logo: `https://img.logo.dev/edf.fr?token=${LOGO_TOKEN}`,
  },
  {
    id: '2',
    provider: 'Luko',
    type: 'Assurance Habitation',
    category: 'insurance',
    status: 'active',
    price: '12€/mois',
    nextDate: '01 Juin 2026',
    icon: 'Shield',
    logo: `https://img.logo.dev/luko.eu?token=${LOGO_TOKEN}`,
  },
  {
    id: '3',
    provider: 'Orange',
    type: 'Box Internet',
    category: 'internet',
    status: 'active',
    price: '39,99€/mois',
    icon: 'Wifi',
    logo: `https://img.logo.dev/orange.fr?token=${LOGO_TOKEN}`,
  },
  {
    id: '4',
    provider: 'Alan',
    type: 'Mutuelle Santé',
    category: 'health',
    status: 'active',
    price: '45€/mois',
    icon: 'Heart',
    logo: `https://img.logo.dev/alan.com?token=${LOGO_TOKEN}`,
  },
  {
    id: '5',
    provider: 'TotalEnergies',
    type: 'Gaz',
    category: 'energy',
    status: 'active',
    price: '55€/mois',
    nextDate: '20 Mars 2026',
    icon: 'Flame',
    logo: `https://img.logo.dev/totalenergies.com?token=${LOGO_TOKEN}`,
  },
];
