export interface Advantage {
  id: string;
  brand: string;
  logo: string;
  discount: string;
  description: string;
  fullDescription: string;
  category: string;
  color: string;
  code?: string;
  validUntil: string;
  image: string;
}

export interface Contract {
  id: string;
  provider: string;
  type: string;
  category: 'energy' | 'insurance' | 'internet' | 'health' | 'other';
  status: 'active' | 'pending' | 'expired';
  price?: string;
  nextDate?: string;
  icon: string;
  logo: string;
}

const LOGO_TOKEN = 'pk_PVnaUxNJTB2AFk6oaM2Cug';

export const advantages: Advantage[] = [
  {
    id: '1',
    brand: 'IKEA',
    logo: `https://img.logo.dev/ikea.com?token=${LOGO_TOKEN}`,
    discount: '-15%',
    description: 'Sur toute la décoration',
    fullDescription: 'Profitez de 15% de réduction sur l\'ensemble du rayon décoration IKEA. Valable en magasin et en ligne sur présentation de votre code promo exclusif.',
    category: 'Maison',
    color: '#0058a3',
    code: 'LOC15DECO',
    validUntil: '31 Mars 2026',
    image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80',
  },
  {
    id: '2',
    brand: 'Adidas',
    logo: `https://img.logo.dev/adidas.com?token=${LOGO_TOKEN}`,
    discount: '-20%',
    description: 'Code promo exclusif',
    fullDescription: 'Bénéficiez de 20% de réduction sur toute la collection Adidas. Chaussures, vêtements et accessoires inclus. Non cumulable avec d\'autres offres.',
    category: 'Sport',
    color: '#000000',
    code: 'JADORELOC20',
    validUntil: '15 Avril 2026',
    image: 'https://images.unsplash.com/photo-1556906781-9a412961c28c?w=800&q=80',
  },
  {
    id: '3',
    brand: 'Castorama',
    logo: `https://img.logo.dev/castorama.fr?token=${LOGO_TOKEN}`,
    discount: '-10%',
    description: 'Bricolage et jardinage',
    fullDescription: 'Réduction de 10% sur tous vos achats bricolage et jardinage. Idéal pour aménager votre nouveau logement. Offre valable en magasin.',
    category: 'Maison',
    color: '#0066cc',
    code: 'CASTO10LOC',
    validUntil: '30 Juin 2026',
    image: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800&q=80',
  },
  {
    id: '4',
    brand: 'Darty',
    logo: `https://img.logo.dev/darty.com?token=${LOGO_TOKEN}`,
    discount: '-15%',
    description: 'Électroménager',
    fullDescription: 'Équipez votre logement avec 15% de réduction sur tout l\'électroménager : réfrigérateur, lave-linge, four, aspirateur et plus encore.',
    category: 'High-Tech',
    color: '#e30613',
    code: 'DARTY15NEW',
    validUntil: '28 Février 2026',
    image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80',
  },
  {
    id: '5',
    brand: 'Uber Eats',
    logo: `https://img.logo.dev/ubereats.com?token=${LOGO_TOKEN}`,
    discount: '-5€',
    description: 'Première commande',
    fullDescription: '5€ offerts sur votre première commande Uber Eats. Faites-vous livrer vos plats préférés directement chez vous.',
    category: 'Food',
    color: '#06c167',
    code: 'BIENVENUE5',
    validUntil: '31 Décembre 2026',
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&q=80',
  },
  {
    id: '6',
    brand: 'Basic-Fit',
    logo: `https://img.logo.dev/basic-fit.com?token=${LOGO_TOKEN}`,
    discount: '1 mois',
    description: 'Offert sur abonnement',
    fullDescription: 'Votre premier mois d\'abonnement offert dans toutes les salles Basic-Fit. Accès illimité 24h/24 et 7j/7.',
    category: 'Sport',
    color: '#ff6600',
    validUntil: '30 Avril 2026',
    image: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&q=80',
  },
  {
    id: '7',
    brand: 'Fnac',
    logo: `https://img.logo.dev/fnac.com?token=${LOGO_TOKEN}`,
    discount: '-10%',
    description: 'Livres et multimédia',
    fullDescription: '10% de réduction sur les livres, CD, vinyles et produits multimédia. Carte Fnac non requise pour cette offre.',
    category: 'Culture',
    color: '#e1a400',
    code: 'FNAC10LOC',
    validUntil: '15 Mai 2026',
    image: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800&q=80',
  },
  {
    id: '8',
    brand: 'Leroy Merlin',
    logo: `https://img.logo.dev/leroymerlin.fr?token=${LOGO_TOKEN}`,
    discount: '-12%',
    description: 'Aménagement intérieur',
    fullDescription: 'Profitez de 12% de réduction pour aménager et décorer votre intérieur. Peinture, revêtements, luminaires et plus.',
    category: 'Maison',
    color: '#78be20',
    code: 'LEROY12HOME',
    validUntil: '30 Juin 2026',
    image: 'https://images.unsplash.com/photo-1556909114-44e3e70034e2?w=800&q=80',
  },
  {
    id: '9',
    brand: 'Amazon',
    logo: `https://img.logo.dev/amazon.fr?token=${LOGO_TOKEN}`,
    discount: '-10€',
    description: 'Sur votre 1ère commande',
    fullDescription: '10€ de réduction sur votre première commande Amazon de 50€ minimum. Livraison gratuite incluse.',
    category: 'Shopping',
    color: '#ff9900',
    code: 'NEWLOC10',
    validUntil: '31 Décembre 2026',
    image: 'https://images.unsplash.com/photo-1523474253046-8cd2748b5fd2?w=800&q=80',
  },
  {
    id: '10',
    brand: 'Netflix',
    logo: `https://img.logo.dev/netflix.com?token=${LOGO_TOKEN}`,
    discount: '2 mois',
    description: 'Offerts sur abonnement',
    fullDescription: 'Profitez de 2 mois offerts sur votre nouvel abonnement Netflix. Films, séries et documentaires en illimité.',
    category: 'Streaming',
    color: '#e50914',
    validUntil: '30 Juin 2026',
    image: 'https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?w=800&q=80',
  },
  {
    id: '11',
    brand: 'Decathlon',
    logo: `https://img.logo.dev/decathlon.fr?token=${LOGO_TOKEN}`,
    discount: '-15%',
    description: 'Articles de sport',
    fullDescription: '15% de réduction sur tout le magasin Decathlon. Équipement sportif, vêtements et accessoires pour tous les sports.',
    category: 'Sport',
    color: '#0082c3',
    code: 'SPORT15LOC',
    validUntil: '31 Mai 2026',
    image: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=800&q=80',
  },
  {
    id: '12',
    brand: 'Deliveroo',
    logo: `https://img.logo.dev/deliveroo.fr?token=${LOGO_TOKEN}`,
    discount: '-30%',
    description: '3 premières commandes',
    fullDescription: '30% de réduction sur vos 3 premières commandes Deliveroo. Découvrez les meilleurs restaurants de votre quartier.',
    category: 'Food',
    color: '#00ccbc',
    code: 'NEW30',
    validUntil: '31 Décembre 2026',
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80',
  },
  {
    id: '13',
    brand: 'Spotify',
    logo: `https://img.logo.dev/spotify.com?token=${LOGO_TOKEN}`,
    discount: '3 mois',
    description: 'Premium offert',
    fullDescription: '3 mois de Spotify Premium offerts. Musique illimitée sans pub, mode hors connexion et qualité audio supérieure.',
    category: 'Streaming',
    color: '#1db954',
    validUntil: '30 Septembre 2026',
    image: 'https://images.unsplash.com/photo-1611339555312-e607c8352fd7?w=800&q=80',
  },
  {
    id: '14',
    brand: 'Zara',
    logo: `https://img.logo.dev/zara.com?token=${LOGO_TOKEN}`,
    discount: '-20%',
    description: 'Nouvelle collection',
    fullDescription: '20% de réduction sur la nouvelle collection Zara. Mode femme, homme et enfant. En magasin et en ligne.',
    category: 'Mode',
    color: '#000000',
    code: 'ZARA20NEW',
    validUntil: '15 Avril 2026',
    image: 'https://images.unsplash.com/photo-1445205170230-053b83016050?w=800&q=80',
  },
  {
    id: '15',
    brand: 'Sephora',
    logo: `https://img.logo.dev/sephora.fr?token=${LOGO_TOKEN}`,
    discount: '-25%',
    description: 'Beauté et parfums',
    fullDescription: '25% de réduction sur une sélection de produits beauté et parfums. Maquillage, soins et coffrets inclus.',
    category: 'Beauté',
    color: '#000000',
    code: 'BEAUTY25',
    validUntil: '28 Février 2026',
    image: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=800&q=80',
  },
  {
    id: '16',
    brand: 'Boulanger',
    logo: `https://img.logo.dev/boulanger.com?token=${LOGO_TOKEN}`,
    discount: '-10%',
    description: 'High-tech & électro',
    fullDescription: '10% de réduction sur tout le site Boulanger. TV, informatique, petit électroménager et plus encore.',
    category: 'High-Tech',
    color: '#e63312',
    code: 'BOUL10LOC',
    validUntil: '30 Avril 2026',
    image: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=800&q=80',
  },
  {
    id: '17',
    brand: 'Carrefour',
    logo: `https://img.logo.dev/carrefour.fr?token=${LOGO_TOKEN}`,
    discount: '-8%',
    description: 'Courses alimentaires',
    fullDescription: '8% de réduction sur vos courses en ligne Carrefour. Livraison à domicile ou retrait en drive.',
    category: 'Courses',
    color: '#004e9f',
    code: 'COURSES8',
    validUntil: '31 Décembre 2026',
    image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=800&q=80',
  },
  {
    id: '18',
    brand: 'Nike',
    logo: `https://img.logo.dev/nike.com?token=${LOGO_TOKEN}`,
    discount: '-25%',
    description: 'Membres exclusif',
    fullDescription: '25% de réduction pour les nouveaux membres Nike. Chaussures, vêtements et équipements sportifs.',
    category: 'Sport',
    color: '#000000',
    code: 'NIKE25NEW',
    validUntil: '31 Mai 2026',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80',
  },
  {
    id: '19',
    brand: 'H&M',
    logo: `https://img.logo.dev/hm.com?token=${LOGO_TOKEN}`,
    discount: '-15%',
    description: 'Tout le magasin',
    fullDescription: '15% de réduction sur tout le magasin H&M. Mode femme, homme, enfant et maison.',
    category: 'Mode',
    color: '#e50010',
    code: 'HM15LOC',
    validUntil: '30 Avril 2026',
    image: 'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?w=800&q=80',
  },
  {
    id: '20',
    brand: 'Maisons du Monde',
    logo: `https://img.logo.dev/maisonsdumonde.com?token=${LOGO_TOKEN}`,
    discount: '-20%',
    description: 'Déco & mobilier',
    fullDescription: '20% de réduction sur la décoration et le mobilier. Idéal pour meubler et décorer votre nouveau chez-vous.',
    category: 'Maison',
    color: '#000000',
    code: 'MDM20HOME',
    validUntil: '30 Juin 2026',
    image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80',
  },
  {
    id: '21',
    brand: 'Picard',
    logo: `https://img.logo.dev/picard.fr?token=${LOGO_TOKEN}`,
    discount: '-10€',
    description: 'Dès 50€ d\'achat',
    fullDescription: '10€ de réduction dès 50€ d\'achat chez Picard. Surgelés de qualité pour des repas faciles et savoureux.',
    category: 'Food',
    color: '#003d7c',
    code: 'PICARD10',
    validUntil: '31 Mars 2026',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
  },
  {
    id: '22',
    brand: 'Zalando',
    logo: `https://img.logo.dev/zalando.fr?token=${LOGO_TOKEN}`,
    discount: '-15%',
    description: 'Mode en ligne',
    fullDescription: '15% de réduction sur votre première commande Zalando. Plus de 2000 marques de mode disponibles.',
    category: 'Mode',
    color: '#ff6900',
    code: 'ZALANDO15',
    validUntil: '31 Décembre 2026',
    image: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=800&q=80',
  },
  {
    id: '23',
    brand: 'Conforama',
    logo: `https://img.logo.dev/conforama.fr?token=${LOGO_TOKEN}`,
    discount: '-100€',
    description: 'Dès 500€ d\'achat',
    fullDescription: '100€ de réduction dès 500€ d\'achat. Meubles, literie, électroménager pour équiper votre logement.',
    category: 'Maison',
    color: '#e4002b',
    code: 'CONFO100',
    validUntil: '30 Avril 2026',
    image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80',
  },
  {
    id: '24',
    brand: 'Nocibé',
    logo: `https://img.logo.dev/nocibe.fr?token=${LOGO_TOKEN}`,
    discount: '-30%',
    description: '2ème parfum',
    fullDescription: '-30% sur le 2ème parfum acheté. Large sélection de grandes marques de parfumerie.',
    category: 'Beauté',
    color: '#e91e8c',
    code: 'NOCIBE30',
    validUntil: '14 Février 2026',
    image: 'https://images.unsplash.com/photo-1541643600914-78b084683601?w=800&q=80',
  },
];

export const contracts: Contract[] = [
  {
    id: '1',
    provider: 'EDF',
    type: 'Énergie',
    category: 'energy',
    status: 'active',
    price: '85€/mois',
    nextDate: '15 Mars 2026',
    icon: 'Zap',
    logo: `https://img.logo.dev/edf.fr?token=${LOGO_TOKEN}`,
  },
  {
    id: '2',
    provider: 'Luko',
    type: 'Assurance Habitation',
    category: 'insurance',
    status: 'active',
    price: '12€/mois',
    nextDate: '01 Juin 2026',
    icon: 'Shield',
    logo: `https://img.logo.dev/luko.eu?token=${LOGO_TOKEN}`,
  },
  {
    id: '3',
    provider: 'Orange',
    type: 'Box Internet',
    category: 'internet',
    status: 'active',
    price: '39,99€/mois',
    icon: 'Wifi',
    logo: `https://img.logo.dev/orange.fr?token=${LOGO_TOKEN}`,
  },
  {
    id: '4',
    provider: 'Alan',
    type: 'Mutuelle Santé',
    category: 'health',
    status: 'active',
    price: '45€/mois',
    icon: 'Heart',
    logo: `https://img.logo.dev/alan.com?token=${LOGO_TOKEN}`,
  },
  {
    id: '5',
    provider: 'TotalEnergies',
    type: 'Gaz',
    category: 'energy',
    status: 'active',
    price: '55€/mois',
    nextDate: '20 Mars 2026',
    icon: 'Flame',
    logo: `https://img.logo.dev/totalenergies.com?token=${LOGO_TOKEN}`,
  },
];
